spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblio_alexandria
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Arthur2806
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081