CREATE DATABASE IF NOT EXISTS biblio_alexandria;
USE biblio_alexandria;

CREATE TABLE IF NOT EXISTS Usuario(
	usuario_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	senha VARCHAR(255) NOT NULL,
	telefone VARCHAR(18) UNIQUE,
	alerta BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Autor(
	autor_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	biografia TEXT NOT NULL,
	nacionalidade VARCHAR(255) NOT NULL,
	data_nascimento DATE NOT NULL,
	data_morte DATE    
);

CREATE TABLE IF NOT EXISTS Livro(
	livro_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	titulo VARCHAR(255) NOT NULL,
	descricao TEXT NOT NULL,
	nota DECIMAL(4, 2) NOT NULL DEFAULT 0.00,
	ano YEAR NOT NULL,
	autor BIGINT NOT NULL,
	FOREIGN KEY(autor) REFERENCES Autor(autor_id)
);

CREATE TABLE IF NOT EXISTS Avaliacao(
	avaliacao_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	nota DECIMAL(4, 2) NOT NULL,
	usuario BIGINT NOT NULL,
	livro BIGINT NOT NULL,
	FOREIGN KEY(usuario) REFERENCES Usuario(usuario_id),
	FOREIGN KEY(livro) REFERENCES Livro(livro_id)
);

CREATE TABLE IF NOT EXISTS Emprestimo(
	emprestimo_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	data_emprestimo DATETIME NOT NULL,
	data_devolucao DATE NOT NULL,
	usuario BIGINT NOT NULL,
	livro BIGINT NOT NULL,
	FOREIGN KEY(usuario) REFERENCES Usuario(usuario_id),
	FOREIGN KEY(livro) REFERENCES Livro(livro_id)
);